### ISSUE TITLE
Running locally with scissors

### ISSUE THREAD

**Issue by butterflyology** [rhodyrstats/geospatial_with_sf#1]
Two very minor issues that may stump learners new to `R` and `knitr`:

1. The page won't knit because `chunk 3` is set to `eval = FALSE` so those building at home will not have the data. Suggest a note in `README.md` that tells them to switch to `eval = TRUE` or to download the code before running `knitr`.
1. In `chunk 10` the file `big.shp` does not exist in the `data/` directory. Suggest changing to file `muni97d.shp`. You still se a difference in load times using `st_read` as opposed to `readOGR`.

**Comment by jhollist** [comment]
I think I got these changes taken care of.  I through in some extra chunks that don't echo, check for the presence of the files and download/create if not there.

I wanted to keep the millions points because Dr. Evil!

Thanks again for helping to clean this up!
